### PR TITLE
add second derivative function and matching test for akima splines

### PR DESCRIPTION
**Pull request by juddmehr**
Added a second derivative function `derivative2` (simply manually took derivative of output expression for derivative function: p1 + 2*p2*dx + 3*p3*dx^2 --> 2*p2 + 6*p3*dx)
Added a test analogous to the basic test for derivative, nothing broke, all tests passed
Added `derivative2` to the exports list

### CODE REVIEW

**Review by andrewning — COMMENTED** [review]
Looks good. how about second_derivative?  too verbose?  derivative2 sounds like a second approach to computing the derivative

**Review by andrewning — COMMENTED** [review]
I should add - you'll need to update the docs too.

**Comment by juddmehr** [comment]
I originally had it as second_derivative, but thought it might be too long.  I agree it's confusing as derivative2.  I'll change it back.
I'll update the appropriate docs sections soon.

**Comment by juddmehr** [comment]
I've updated the function name and added the example and docstring to the docs with the other derivative methods.

**Pull request merged**
