### PR TITLE
Kreisselmeier–steinhauser

### PR DESCRIPTION
**Pull request by taylormcd**
Adds Kreisselmeier-steinhauser constraint aggregation function.  Also fixes some Julia 1.0 issues.

### CODE REVIEW

**Comment by andrewning** [comment]
Can you add a corresponding update to the README (small amount of documentation/example).

**Comment by taylormcd** [comment]
done

**Comment by andrewning** [comment]
2 more comments:
- might be worth noting that this is the modified KS function, which is what I use too (I think the original didn't have the parameter you call k).
- would be nice to have two functions since we don't always maximize. I'd rename this one ksmax and then add one called ksmin.  Something like:
```ksmin(x, hardness) = -ksmax(-x, hardness)```

**Comment by andrewning** [comment]
should we have a default value for hardness?  I recall a paper where from their studies they recommended 50 as a reasonable starting default.

**Comment by taylormcd** [comment]
The parameter I call `k` (which is just the maximum of the inputs) is necessary to avoid numerical overflow/underflow.  The modified form is mathematically identical to the original function.  I'll add ksmin and ksmax.

**Comment by taylormcd** [comment]
I also added a default hardness of 50.

**Comment by andrewning** [comment]
yeah I know what k is for, it just is called an alternate or modified as the original form didn't have it.

looks great.

**Pull request merged**
